src/Ekologia/MenuBundle/Entity/Menu.php
<?php

namespace Ekologia\MenuBundle\Entity;

use Doctrine\ORM\Mapping as ORM;

/**
 * Menu
 *
 * @ORM\Table(name="eko_menu")
 * @ORM\Entity(repositoryClass="Ekologia\MenuBundle\Entity\MenuRepository")
 */
class Menu {

    /**
     * @var integer
     *
     * @ORM\Column(name="id", type="integer")
     * @ORM\Id
     * @ORM\GeneratedValue(strategy="AUTO")
     */
    private $id;

    /**
     * @var string
     * 
     * @ORM\Column(name="name", type="string")
     */
    private $name;

    /**
     * @var string
     * 
     * @ORM\Column(name="route", type="string")
     */
    private $route;

    /**
     * @var integer
     * 
     * @ORM\ManyToOne(targetEntity="Ekologia\MenuBundle\Entity\Menu", inversedBy="children")
     * @ORM\JoinColumn(nullable = true)
     */
    private $parent;

    /**
     * @ORM\OneToMany(targetEntity="Ekologia\MenuBundle\Entity\Menu", cascade={"persist"}, mappedBy="parent")
     */
    private $children;

    /**
     * 
     * @ORM\Column(name="parameters", type="json_array", nullable=true)
     */
    private $parameters;

    /**
     * @var string
     * 
     * @ORM\Column(name="language", type="string", length=255, nullable=true)
     */
    protected $language;

    /**
     * @var integer
     * 
     * @ORM\Column(name="order", type="integer", nullable=false)
     */
    protected $order;

    /**
     * Get id
     *
     * @return integer 
     */
    public function getId() {
        return $this->id;
    }

    public function getName() {
        return $this->name;
    }

    public function getRoute() {
        return $this->route;
    }

    public function getParent() {
        return $this->parent;
    }

    public function getParameters() {
        return $this->parameters;
    }

    public function setName($name) {
        $this->name = $name;
    }

    public function setRoute($route) {
        $this->route = $route;
    }

    public function setParent($parent) {
        $this->parent = $parent;
    }

    public function setParameters($parameters) {
        $this->parameters = $parameters;
    }

    /**
     * Constructor
     */
    public function __construct() {
        $this->children = new \Doctrine\Common\Collections\ArrayCollection();
    }

    /**
     * Add children
     *
     * @param \Ekologia\MenuBundle\Entity\Menu $children
     * @return Menu
     */
    public function addChild(\Ekologia\MenuBundle\Entity\Menu $children) {
        $this->children[] = $children;

        return $this;
    }

    /**
     * Remove children
     *
     * @param \Ekologia\MenuBundle\Entity\Menu $children
     */
    public function removeChild(\Ekologia\MenuBundle\Entity\Menu $children) {
        $this->children->removeElement($children);
    }

    /**
     * Get children
     *
     * @return \Doctrine\Common\Collections\Collection 
     */
    public function getChildren() {
        return $this->children;
    }

    /**
     * Set menu language
     * 
     * @param string $language
     * @return \Ekologia\MenuBundle\Entity\Menu This object
     */
    public function setLanguage($language) {
        $this->language = $language;
        return $this;
    }

    /**
     * Get menu language
     * 
     * @return string
     */
    public function getLanguage() {
        return $this->language;
    }

    /**
     * Set menu order
     * 
     * @param integer $order
     * @return \Ekologia\MenuBundle\Entity\Menu This object
     */
    public function setOrder($order) {
        $this->order = $order;
        return $this;
    }

    /**
     * Get menu order
     * 
     * @return integer
     */
    public function getOrder() {
        return $this->order;
    }
    
    public function getOrderedChildren() {
        $children = $this->getChildren()->toArray();
        usort($children, function($c1, $c2){
            return $c1->getOrder() - $c2->getOrder();
        });
        return $children;
    }
}

src/Ekologia/MenuBundle/Entity/MenuRepository.php
<?php

namespace Ekologia\MenuBundle\Entity;

use Doctrine\ORM\EntityRepository;

/**
 * Provide methods for querying Menu
 */
class MenuRepository extends EntityRepository {
    /**
     * Finds the main menu in terms of given name.
     * 
     * @param string $name The name menu to find
     */
    public function findParent($name, $language) {
        return $this->findOneBy(array('parent' => null, 'name' => $name, 'language' => $language));
    }
}

src/Ekologia/MenuBundle/Controller/MenuController.php
<?php

namespace Ekologia\MenuBundle\Controller;

use Ekologia\MainBundle\Controller\MasterController;

class MenuController extends MasterController {

    public function indexAction() {
        return $this->render('EkologiaMenuBundle:GestionMenus:arborescenceMenu.html.twig');
    }

    /**
     * Get the Json from the tree
     */
    public function treePageAction($parent){
        $em = $this->getDoctrine()->getManager();
        $listeMenu = $em->getRepository("EkologiaMenuBundle:Menu")->findOneBy(array('parent' => null, 'name' => $parent));
        $treeMenu = $this->listeMenuToTree($listeMenu->getChildren());
        return $this->jsonResponse($treeMenu);
    }
    
    /**
     * Convert a list to a tree
     */
    public function listeMenuToTree($listeMenu) {
        $result = array();

        foreach ($listeMenu as $menu) {
            $result[] = array(
                'id' => $menu->getId(),
                'name' => $menu->getName(),
                'route' => $menu->getRoute(),
                'parameters' => $menu->getParameters(),
                'children' => $this->listeMenuToTree($menu->getChildren())
            );
        }
        return $result;
    }

    /**
     * à ajouter
     * Create action (création avec champ vide sauf champ obligatoires)
     * Update action (sera le plus utilisé, récupération des données avec ajax ?)
     * Delete action (delete par l'id     
     */
}

src/Ekologia/MenuBundle/Controller/ViewController.php
<?php
namespace Ekologia\MenuBundle\Controller;

use Ekologia\MainBundle\Controller\MasterController;
use Symfony\Component\HttpFoundation\Request;

/**
 * This controller provide some methods to show menu in this site
 */
class ViewController extends MasterController {
    public function rootAction(Request $request) {
        $menu = $this->getDoctrine()->getRepository('EkologiaMenuBundle:Menu')->findParent('root', $request->getLocale());
        return $this->render('EkologiaMenuBundle:View:navbar.html.twig', array('menu' => $menu));
    }
}

src/Ekologia/MenuBundle/Tests/Controller/DefaultControllerTest.php
<?php

namespace Ekologia\MenuBundle\Tests\Controller;

use Symfony\Bundle\FrameworkBundle\Test\WebTestCase;

class DefaultControllerTest extends WebTestCase
{
    public function testIndex()
    {
        $client = static::createClient();

        $crawler = $client->request('GET', '/hello/Fabien');

        $this->assertTrue($crawler->filter('html:contains("Hello Fabien")')->count() > 0);
    }
}

src/Ekologia/MenuBundle/Resources/views/GestionMenus/arborescenceMenu.html.twig
{% extends '::base.html.twig' %}
{% block stylesheets %}

    <link rel="stylesheet" href="{{ asset('js/jstree/dist/themes/default/style.min.css') }}" />    

{% endblock %}
{% block javascripts %}
    <script type="text/javascript" src="{{ asset('js/jquery.js') }}"></script>
    <script type="text/javascript" src="{{ asset('js/jstree/dist/jstree.min.js') }}"></script>
    <script type="text/javascript">
        $(function() {
            $('#toto').jstree({
                "core": {
                    "animation": 0,
                    "check_callback": true,
                    "themes": {"stripes": true},
                    'data': {
                        'url': function(node) {
                            return node.id === '#' ?
                                    'ajax_demo_roots.json' : 'ajax_demo_children.json';
                        },
                        'data': function(node) {
                            return {'id': node.id};
                        }
                    }
                },
                "types": {
                    "#": {
                        "max_children": 1,
                        "valid_children": ["root"]
                    },
                    "root": {
                        "icon": "/static/3.0.2/assets/images/tree_icon.png",
                        "valid_children": ["default"]
                    },
                    "default": {
                        "valid_children": ["default", "file"]
                    },
                    "file": {
                        "icon": "glyphicon glyphicon-file",
                        "valid_children": []
                    }
                },
                "plugins": [
                    "contextmenu", "dnd", "search",
                    "state", "types", "wholerow"
                ]
            });
            $('#jstree').jstree();

            $('#jstree').on("changed.jstree", function(e, data) {
                console.log(data.selected);
            });

            $('#jstree').jstree(true).select_node('child_node_1');
            $('#jstree').jstree('select_node', 'child_node_1');
            $.jstree.reference('#jstree').select_node('child_node_1');

        });
    </script>
{% endblock %}

{% block body %}

    {% for menu in listeMenu %}
        <div> {{ menu.id ~ " " ~ menu.name }} </div>
    {% endfor %}

    <div id="jstree"> 
        <ul>
            <li> Root node1
                <ul>
                    <li id="child_node_1">Child node 1</li>
                    <li>Child node 2</li>
                </ul>
            </li>
        </ul>
    </div>


{% endblock %}

src/Ekologia/MenuBundle/Resources/views/View/navbar.html.twig
<ul class="nav nav-pills">
    {% for child in menu.orderedChildren %}
        {% if child.children|length > 0 %}
            <li class="dropdown">
                <a href="#" class="dropdown-toggle" data-toggle="dropdown">
                    {{ child.name }} <span class="caret"></span>
                </a>
                <ul class="dropdown-menu multi-level">
                    {% for subchild in child.orderedChildren %}
                        {% if subchild.parameters is defined %}
                            <li><a href="{{ path(subchild.route, subchild.parameters) }}">{{ subchild.name }}</a></li>
                        {% else %}
                            <li><a href="{{ path(subchild.route) }}">{{ subchild.name }}</a></li>
                        {% endif %}
                    {% endfor %}
                </ul>
            </li>
        {% else %}
            <li><a href="{{ path(child.route, child.parameters) }}">{{ child.name }}</a></li>
        {% endif %}
    {% endfor %}
</ul>